### ISSUE TITLE
pagure: support new way of creating PRs from forks

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#161]
https://src.stg.fedoraproject.org/api/0/#pull-requests

we just need to use the new fields such as repo_from which were added to the API in order to create PRs from forks to parent repos.

follow up to https://github.com/packit-service/packit/pull/496
blocks https://github.com/packit-service/packit.dev/pull/42

likely packit will need some code changes to support this

**Comment by lachmanfrantisek** [comment]
@TomasTomecek I am not sure if need to change anything:

> Open a new pull-request from this project to itself or its parent (if this project is a fork).

Since we are using the default behaviour, it means:

- Using the `origin` instance, it will create a pull-request from `origin` to `origin`.
- Using the instance of the `fork`, it will create a pull-request from `fork` to `origin`.
- **We are missing the functionality to create pull-request from `fork` to `fork` itself and from `fork` to `origin` using the `origin` instance (=with the token from the `origin` repo?). Is that what we need?**

**Comment by TomasTomecek** [comment]
> Using the instance of the fork, it will create a pull-request from fork to origin.

It won't, try it on stg. Pagure 5.7 changed this.

Reproducer: https://pagure.io/fedora-infrastructure/issue/8115#comment-591170

**Comment by lachmanfrantisek** [comment]
> It won't, try it on stg. Pagure 5.7 changed this.

Do I get it right, that this is a bug on the Pagure site? So I am not sure how you want to fix that. (We can discuss that tomorrow in person.)

**Comment by TomasTomecek** [comment]
yes, let's discuss in person

**Comment by lachmanfrantisek** [comment]
OK, the docs are outdated and the current version works by default fork->fork when running from fork and upstream->upstream when running from upstream.

We need to use the `repo_from` fields to be able to achieve our `fork->upstream` approach. (We agreed that we want to leave the current API of OGR as is and fix only the implementation.)
