### ISSUE TITLE
Fix createing pull requests in GitHub

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/ogr#250]
The default behaviour should be:

- running from fork:
    - create pr from fork to upstream
- running from upstream:
    - create pr from upstream to upstream

We need to specify correctly the username in `head` or use the correct pygithub object to call the `create_pull` on.

- Get inspired in packit: https://github.com/packit-service/packit/blob/master/packit/upstream.py#L190
- API docs: https://developer.github.com/v3/pulls/#create-a-pull-request (`head` parameter)
- Related pygithub method: https://pygithub.readthedocs.io/en/latest/github_objects/Repository.html#github.Repository.Repository.create_pull

AC:

- [ ] check the existing workflow
- [ ] fix the username to support both workflows correctly
- [ ] create tests for both of them

**Comment by sakalosj** [comment]
Hi,

i have created some first shot for this issue. question is what will break this changhe. At least  https://github.com/packit-service/packit/blob/master/packit/upstream.py#L190 will need be updated - i can do it once we you will have final solution.

I didnt create integration tests - because of this function involves pull-request creation i didnt wanted to mess with repositories. Instead i have added some unit tests.

**Comment by lachmanfrantisek** [comment]
Fixed in https://github.com/packit-service/ogr/pull/269 thanks to @sakalosj
