### ISSUE TITLE
Improve testing

### ISSUE THREAD

**Issue by TomasTomecek** [packit-service/ogr#8]
* [x] don't fail when PAGURE_{TOKEN,USER} are not specified
* [x] mock remote API and write complete unit tests using those data (or even have a single test suite and enable it to run against live instance and mocked data)
* [x] [tox](https://developer.fedoraproject.org/tech/languages/python/multiple-pythons.html)-ify it (#27)

**Comment by jscotka** [comment]
first issue solved by: https://github.com/packit-service/ogr/pull/30

**Comment by jscotka** [comment]
otherwise, **unit tests** does not need to have any env_vars to be set. so it works well.

It is required inside **integration test**.

I think that solution that some part of integration tests will **mock** env and then there will be another part what needs to have credentials is completely fine, because in this case of library, also real E2E tests are important.
